### ISSUE TITLE
BUG:  The promised code is missing.  

### ISSUE THREAD

**Issue by richlysakowski** [PacktPublishing/OpenAI-API-Cookbook#5]
Don't make promises you don't keep.  

You broke the trust with me as a buyer.

**Comment by yashpackt** [comment]
Hello @richlysakowski, we apologize deeply for not keeping our promise and breaking your trust as a buyer. It was not our intention to let you down, and we understand the disappointment this has caused. 
We have uploaded the code files of each chapters and you can check them out.
Your satisfaction is important to us, and we are genuinely sorry for any inconvenience caused. Do reach out to us again in case of any issues.
